# Generated by Django 4.2 on 2023-05-04 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnigmaMachine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='MessagesReceived', to=settings.AUTH_USER_MODEL),
        ),
    ]
